### PR TITLE
set a local user.email so tests work for developers that require this…

### PR DESCRIPTION
**Pull request by sleifer**
… setting

Some of the unit tests failed for me because I have my local world set up to require a local user.email configuration. This commit makes sure one is set where needed.

### CODE REVIEW

**Comment by bsneed** [comment]
what is the effect of this on the follow on commands in the test?  I'm not too familiar with how this affects git outside of the commit stage.

**Comment by sleifer** [comment]
The effect of the command is to add the following two lines to .git/config, so local to the test repo:

[user]
	email = foo@example.com

I have a pre-commit hook checking for the existence of the setting and will fail commits if it is not present. I'd imagine I'm in the minority doing thing this.

The only effect should be to have the email address associated with the commits later in the test be foo@example.com instead of what the user configured in ~/.gitconfig. Since we're not testing for the email address of the committer and the repo goes away at the end of the test it shouldn't alter the results and should be contained to the the runtime of the test.

**Comment by bsneed** [comment]
do all the other tests run for you without this?  this doesn't seem like the right solution, as people could have all kinds of githooks.  is it possible to just disable githooks as a whole for a single repo?

**Comment by bsneed** [comment]
looks like `commit --no-verify` on the commit command line is the way to go.  looks like it bypasses the pre/post commit hooks.

**Comment by sleifer** [comment]
All the other tests run for me without it. I didn't see a way on the front end to prevent globally configured hooks from being set up. Agreed, --no-verify is a broader solution. I'll switch to that.

**Comment by bsneed** [comment]
sounds good.  I guess at some point we should wrap all these common commands so we get the same flags throughout our test suite.  not necessary now, but something to think about for future improvements.

i.e.: `runCommand("git commit -m \(something)--no-verify")` scattered throughout instead becomes `testGit.commit(something)`

**Comment by sleifer** [comment]
switched to --no-verify. I bottle necked all commits in tests by adding a new func next to the global runCommand func. -- all unit tests pass for me

**Comment by bsneed** [comment]
it still shows the setting of a local email address in the diff.  were you going to remove that?

**Comment by sleifer** [comment]
I did, but somewhere in squashing and pushing git is getting the better of me. I'm going to make a fresh branch and pull request.

**Pull request closed without merging**
